# CMake generated Testfile for 
# Source directory: /home/thahn1230/llama.cpp/tests
# Build directory: /home/thahn1230/llama.cpp/build-android/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test-tokenizer-0-bert-bge "/home/thahn1230/llama.cpp/build-android/bin/test-tokenizer-0" "/home/thahn1230/llama.cpp/tests/../models/ggml-vocab-bert-bge.gguf")
set_tests_properties(test-tokenizer-0-bert-bge PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/thahn1230/llama.cpp/tests/CMakeLists.txt;36;add_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;86;llama_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-command-r "/home/thahn1230/llama.cpp/build-android/bin/test-tokenizer-0" "/home/thahn1230/llama.cpp/tests/../models/ggml-vocab-command-r.gguf")
set_tests_properties(test-tokenizer-0-command-r PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/thahn1230/llama.cpp/tests/CMakeLists.txt;36;add_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;87;llama_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-deepseek-coder "/home/thahn1230/llama.cpp/build-android/bin/test-tokenizer-0" "/home/thahn1230/llama.cpp/tests/../models/ggml-vocab-deepseek-coder.gguf")
set_tests_properties(test-tokenizer-0-deepseek-coder PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/thahn1230/llama.cpp/tests/CMakeLists.txt;36;add_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;88;llama_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-deepseek-llm "/home/thahn1230/llama.cpp/build-android/bin/test-tokenizer-0" "/home/thahn1230/llama.cpp/tests/../models/ggml-vocab-deepseek-llm.gguf")
set_tests_properties(test-tokenizer-0-deepseek-llm PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/thahn1230/llama.cpp/tests/CMakeLists.txt;36;add_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;89;llama_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-falcon "/home/thahn1230/llama.cpp/build-android/bin/test-tokenizer-0" "/home/thahn1230/llama.cpp/tests/../models/ggml-vocab-falcon.gguf")
set_tests_properties(test-tokenizer-0-falcon PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/thahn1230/llama.cpp/tests/CMakeLists.txt;36;add_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;90;llama_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-gpt-2 "/home/thahn1230/llama.cpp/build-android/bin/test-tokenizer-0" "/home/thahn1230/llama.cpp/tests/../models/ggml-vocab-gpt-2.gguf")
set_tests_properties(test-tokenizer-0-gpt-2 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/thahn1230/llama.cpp/tests/CMakeLists.txt;36;add_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;91;llama_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-llama-bpe "/home/thahn1230/llama.cpp/build-android/bin/test-tokenizer-0" "/home/thahn1230/llama.cpp/tests/../models/ggml-vocab-llama-bpe.gguf")
set_tests_properties(test-tokenizer-0-llama-bpe PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/thahn1230/llama.cpp/tests/CMakeLists.txt;36;add_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;92;llama_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-llama-spm "/home/thahn1230/llama.cpp/build-android/bin/test-tokenizer-0" "/home/thahn1230/llama.cpp/tests/../models/ggml-vocab-llama-spm.gguf")
set_tests_properties(test-tokenizer-0-llama-spm PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/thahn1230/llama.cpp/tests/CMakeLists.txt;36;add_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;93;llama_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-mpt "/home/thahn1230/llama.cpp/build-android/bin/test-tokenizer-0" "/home/thahn1230/llama.cpp/tests/../models/ggml-vocab-mpt.gguf")
set_tests_properties(test-tokenizer-0-mpt PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/thahn1230/llama.cpp/tests/CMakeLists.txt;36;add_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;94;llama_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-nomic-bert-moe "/home/thahn1230/llama.cpp/build-android/bin/test-tokenizer-0" "/home/thahn1230/llama.cpp/tests/../models/ggml-vocab-nomic-bert-moe.gguf")
set_tests_properties(test-tokenizer-0-nomic-bert-moe PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/thahn1230/llama.cpp/tests/CMakeLists.txt;36;add_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;95;llama_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-phi-3 "/home/thahn1230/llama.cpp/build-android/bin/test-tokenizer-0" "/home/thahn1230/llama.cpp/tests/../models/ggml-vocab-phi-3.gguf")
set_tests_properties(test-tokenizer-0-phi-3 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/thahn1230/llama.cpp/tests/CMakeLists.txt;36;add_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;96;llama_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-qwen2 "/home/thahn1230/llama.cpp/build-android/bin/test-tokenizer-0" "/home/thahn1230/llama.cpp/tests/../models/ggml-vocab-qwen2.gguf")
set_tests_properties(test-tokenizer-0-qwen2 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/thahn1230/llama.cpp/tests/CMakeLists.txt;36;add_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;97;llama_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-refact "/home/thahn1230/llama.cpp/build-android/bin/test-tokenizer-0" "/home/thahn1230/llama.cpp/tests/../models/ggml-vocab-refact.gguf")
set_tests_properties(test-tokenizer-0-refact PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/thahn1230/llama.cpp/tests/CMakeLists.txt;36;add_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;98;llama_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-starcoder "/home/thahn1230/llama.cpp/build-android/bin/test-tokenizer-0" "/home/thahn1230/llama.cpp/tests/../models/ggml-vocab-starcoder.gguf")
set_tests_properties(test-tokenizer-0-starcoder PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/thahn1230/llama.cpp/tests/CMakeLists.txt;36;add_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;99;llama_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-sampling "/home/thahn1230/llama.cpp/build-android/bin/test-sampling")
set_tests_properties(test-sampling PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/thahn1230/llama.cpp/tests/CMakeLists.txt;74;add_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;107;llama_build_and_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-grammar-parser "/home/thahn1230/llama.cpp/build-android/bin/test-grammar-parser")
set_tests_properties(test-grammar-parser PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/thahn1230/llama.cpp/tests/CMakeLists.txt;74;add_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;108;llama_build_and_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-grammar-integration "/home/thahn1230/llama.cpp/build-android/bin/test-grammar-integration")
set_tests_properties(test-grammar-integration PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/thahn1230/llama.cpp/tests/CMakeLists.txt;74;add_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;109;llama_build_and_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-llama-grammar "/home/thahn1230/llama.cpp/build-android/bin/test-llama-grammar")
set_tests_properties(test-llama-grammar PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/thahn1230/llama.cpp/tests/CMakeLists.txt;74;add_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;110;llama_build_and_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-chat "/home/thahn1230/llama.cpp/build-android/bin/test-chat")
set_tests_properties(test-chat PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/thahn1230/llama.cpp/tests/CMakeLists.txt;74;add_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;111;llama_build_and_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-json-schema-to-grammar "/home/thahn1230/llama.cpp/build-android/bin/test-json-schema-to-grammar")
set_tests_properties(test-json-schema-to-grammar PROPERTIES  LABELS "main" WORKING_DIRECTORY "/home/thahn1230/llama.cpp/tests/.." _BACKTRACE_TRIPLES "/home/thahn1230/llama.cpp/tests/CMakeLists.txt;74;add_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;114;llama_build_and_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-1-llama-spm "/home/thahn1230/llama.cpp/build-android/bin/test-tokenizer-1-spm" "/home/thahn1230/llama.cpp/tests/../models/ggml-vocab-llama-spm.gguf")
set_tests_properties(test-tokenizer-1-llama-spm PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/thahn1230/llama.cpp/tests/CMakeLists.txt;36;add_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;140;llama_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-chat-parser "/home/thahn1230/llama.cpp/build-android/bin/test-chat-parser")
set_tests_properties(test-chat-parser PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/thahn1230/llama.cpp/tests/CMakeLists.txt;74;add_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;146;llama_build_and_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-chat-template "/home/thahn1230/llama.cpp/build-android/bin/test-chat-template")
set_tests_properties(test-chat-template PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/thahn1230/llama.cpp/tests/CMakeLists.txt;74;add_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;147;llama_build_and_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-json-partial "/home/thahn1230/llama.cpp/build-android/bin/test-json-partial")
set_tests_properties(test-json-partial PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/thahn1230/llama.cpp/tests/CMakeLists.txt;74;add_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;148;llama_build_and_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-log "/home/thahn1230/llama.cpp/build-android/bin/test-log")
set_tests_properties(test-log PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/thahn1230/llama.cpp/tests/CMakeLists.txt;74;add_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;149;llama_build_and_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-regex-partial "/home/thahn1230/llama.cpp/build-android/bin/test-regex-partial")
set_tests_properties(test-regex-partial PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/thahn1230/llama.cpp/tests/CMakeLists.txt;74;add_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;150;llama_build_and_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-arg-parser "/home/thahn1230/llama.cpp/build-android/bin/test-arg-parser")
set_tests_properties(test-arg-parser PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/thahn1230/llama.cpp/tests/CMakeLists.txt;74;add_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;154;llama_build_and_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-gguf "/home/thahn1230/llama.cpp/build-android/bin/test-gguf")
set_tests_properties(test-gguf PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/thahn1230/llama.cpp/tests/CMakeLists.txt;74;add_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;158;llama_build_and_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-backend-ops "/home/thahn1230/llama.cpp/build-android/bin/test-backend-ops")
set_tests_properties(test-backend-ops PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/thahn1230/llama.cpp/tests/CMakeLists.txt;74;add_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;159;llama_build_and_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-model-load-cancel "/home/thahn1230/llama.cpp/build-android/bin/test-model-load-cancel")
set_tests_properties(test-model-load-cancel PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/thahn1230/llama.cpp/tests/CMakeLists.txt;74;add_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;161;llama_build_and_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-autorelease "/home/thahn1230/llama.cpp/build-android/bin/test-autorelease")
set_tests_properties(test-autorelease PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/thahn1230/llama.cpp/tests/CMakeLists.txt;74;add_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;162;llama_build_and_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-barrier "/home/thahn1230/llama.cpp/build-android/bin/test-barrier")
set_tests_properties(test-barrier PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/thahn1230/llama.cpp/tests/CMakeLists.txt;74;add_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;166;llama_build_and_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-quantize-fns "/home/thahn1230/llama.cpp/build-android/bin/test-quantize-fns")
set_tests_properties(test-quantize-fns PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/thahn1230/llama.cpp/tests/CMakeLists.txt;74;add_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;167;llama_build_and_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-quantize-perf "/home/thahn1230/llama.cpp/build-android/bin/test-quantize-perf")
set_tests_properties(test-quantize-perf PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/thahn1230/llama.cpp/tests/CMakeLists.txt;74;add_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;168;llama_build_and_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-rope "/home/thahn1230/llama.cpp/build-android/bin/test-rope")
set_tests_properties(test-rope PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/thahn1230/llama.cpp/tests/CMakeLists.txt;74;add_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;169;llama_build_and_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;0;")
add_test(test-mtmd-c-api "/home/thahn1230/llama.cpp/build-android/bin/test-mtmd-c-api")
set_tests_properties(test-mtmd-c-api PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/thahn1230/llama.cpp/tests/CMakeLists.txt;74;add_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;174;llama_build_and_test;/home/thahn1230/llama.cpp/tests/CMakeLists.txt;0;")
